apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: digino-tanzu
resources:
  - ../../base

patches:
  - target:
      group: ""
      version: v1
      kind: Namespace
      name: digino
    patch: |-
      - op: replace
        path: /metadata/name
        value: digino-tanzu

  - target:
      group: apps
      version: v1
      kind: Deployment
      name: ".*"
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: ".*"
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      group: ""
      version: v1
      kind: PersistentVolumeClaim
      name: postgres-data
    patch: |-
      - op: add
        path: /spec/storageClassName
        value: k8s-local-ds

images:
  - name: novamarket/gateway
    newName: reg.test.local:8090/novamarket/gateway
    newTag: "1.1.2"
  - name: novamarket/frontend
    newName: reg.test.local:8090/novamarket/frontend
    newTag: "1.2.0"
  - name: novamarket/shop
    newName: reg.test.local:8090/novamarket/shop
    newTag: "1.1.0"
  - name: novamarket/product
    newName: reg.test.local:8090/novamarket/product
    newTag: "1.0.0"
  - name: novamarket/about
    newName: reg.test.local:8090/novamarket/about
    newTag: "1.1.0"
  - name: novamarket/account
    newName: reg.test.local:8090/novamarket/account
    newTag: "1.0.0"
  - name: novamarket/orders
    newName: reg.test.local:8090/novamarket/orders
    newTag: "1.0.0"
  - name: novamarket/checkout
    newName: reg.test.local:8090/novamarket/checkout
    newTag: "1.0.0"
  - name: novamarket/admin
    newName: reg.test.local:8090/novamarket/admin
    newTag: "1.0.0"
  - name: novamarket/backend
    newName: reg.test.local:8090/novamarket/backend
    newTag: "1.0.1"
  - name: reg.test.local:8082/novamarket/catalog
    newName: reg.test.local:8090/novamarket/catalog
    newTag: "1.5.0"
  - name: novamarket/cart
    newName: reg.test.local:8090/novamarket/cart
    newTag: "1.1.0"
  - name: novamarket/user
    newName: reg.test.local:8090/novamarket/user
    newTag: "1.1.0"
  - name: novamarket/orders-api
    newName: reg.test.local:8090/novamarket/orders-api
    newTag: "1.1.0"
  - name: novamarket/payment
    newName: reg.test.local:8090/novamarket/payment
    newTag: "1.1.0"
  - name: novamarket/shipping
    newName: reg.test.local:8090/novamarket/shipping
    newTag: "1.1.0"
  - name: novamarket/search
    newName: reg.test.local:8090/novamarket/search
    newTag: "1.1.0"
  - name: novamarket/wishlist
    newName: reg.test.local:8090/novamarket/wishlist
    newTag: "1.1.0"
  - name: novamarket/reviews
    newName: reg.test.local:8090/novamarket/reviews
    newTag: "1.1.0"
  - name: novamarket/notification
    newName: reg.test.local:8090/novamarket/notification
    newTag: "1.1.0"
  - name: novamarket/discount
    newName: reg.test.local:8090/novamarket/discount
    newTag: "1.1.0"
  - name: postgres
    newName: reg.test.local:8090/library/postgres
    newTag: "16.4-alpine"
  - name: reg.test.local:8082/novamarket/db-migrations
    newName: reg.test.local:8090/novamarket/db-migrations
    newTag: "1.0.5"
